### ISSUE TITLE
Does not work on android emulators using any other API level than 26

### ISSUE THREAD

**Issue by renefitzke** [rumax/react-native-PixelsCatcher#82]
**Describe the bug**
Running the snapshot tests on android emulators with any API level other than 26 does not work. The errors vary depending on the API level being used (see below at emulator information).

**To Reproduce**
  - [ ] I checked the demo project and cannot reproduce the issue
  - [x] I checked the demo project and the issue exists

**Steps to reproduce the behavior:**
1. clone https://github.com/renefitzke/IssuesPixelsCatcher
2. yarn install
3. Set the emulator you want to test with up (see below)
4. Adjust pixels-catcher.json according to the emulator you want to test with
5. `cd android && ./gradlew assembleRelease -DentryFile="indexSnapshot.js"`
6. `./node_modules/.bin/pixels-catcher android release`

Experiencing the same behaviour on the demo project.

**Expected behavior**
Tests should run on android emulators regardless of the API level they use.

**Emulator information:**
**Works on:**
_Pixel_4_XL_API_26 (API 26, ABI x86, Android 8.0 (Google APIs))_
_Nexus_6_API_26 (API 26, ABI x86, Android 8.0 (Google APIs))_

**Does not work on:**
_Pixel_4_XL_API_31 (API 31, ABI X86_64, ANDROID 12.0 (Google APIs))_
_Pixel_4_XL_API_30 (API 30, ABI x86, Android 11.0 (Google APIs))_
Error message: `PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator, stderr: WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.`
Console output:
```
PIXELS_CATCHER: Starting with [release] configuration for [android]
PIXELS_CATCHER: Config
{
  "activityName": ".MainActivity",
  "deviceName": "Pixel_4_XL_API_30",
  "packageName": "com.issuespixelscatcher",
  "snapshotsPath": "./snapshotsImages",
  "release": {
    "deviceParams": [
      "-no-audio",
      "-no-snapshot"
    ],
    "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
  }
}
PIXELS_CATCHER: Starting with:
  - activityName: [.MainActivity]
  - appFile: [./android/app/build/outputs/apk/release/app-release.apk]
  - deviceName: [Pixel_4_XL_API_30]
  - deviceParams: [-no-audio,-no-snapshot]
  - packageName: [com.issuespixelscatcher]
  - snapshotsPath: [./snapshotsImages]
  - canStopDevice: [undefined]
  - port: [undefined]
  - locale: [undefined]
PIXELS_CATCHER: Starting in ci mode
PIXELS_CATCHER: Starting server
PIXELS_CATCHER: Start emulator [Pixel_4_XL_API_30]
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Other emulator already started
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Stopping emulator
PIXELS_CATCHER::UTIL_EMULATOR: Stopping active device
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::SERVER: server is listening on port [3000]
PIXELS_CATCHER::UTIL_EMULATOR: Active device stopped
PIXELS_CATCHER::UTIL_EMULATOR: Starting emulator [Pixel_4_XL_API_30]
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator, stderr: WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
```

_Pixel_4_XL_API_28 (API 28, ABI x86, Android 9.0 (Google APIs))_
Emulator and App start regularly but test do not run. Times out after some time.
Console output:
```
PIXELS_CATCHER: Starting with [release] configuration for [android]
PIXELS_CATCHER: Config
{
  "activityName": ".MainActivity",
  "deviceName": "Pixel_4_XL_API_28",
  "packageName": "com.issuespixelscatcher",
  "snapshotsPath": "./snapshotsImages",
  "release": {
    "deviceParams": [
      "-no-audio",
      "-no-snapshot"
    ],
    "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
  }
}
PIXELS_CATCHER: Starting with:
  - activityName: [.MainActivity]
  - appFile: [./android/app/build/outputs/apk/release/app-release.apk]
  - deviceName: [Pixel_4_XL_API_28]
  - deviceParams: [-no-audio,-no-snapshot]
  - packageName: [com.issuespixelscatcher]
  - snapshotsPath: [./snapshotsImages]
  - canStopDevice: [undefined]
  - port: [undefined]
  - locale: [undefined]
PIXELS_CATCHER: Starting in ci mode
PIXELS_CATCHER: Starting server
PIXELS_CATCHER: Start emulator [Pixel_4_XL_API_28]
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: No active devices
PIXELS_CATCHER::UTIL_EMULATOR: Starting emulator [Pixel_4_XL_API_28]
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
- waiting for device -
PIXELS_CATCHER::SERVER: server is listening on port [3000]
PIXELS_CATCHER::UTIL_EMULATOR: stdout: INFO    | configAndStartRenderer: setting vsync to 60 hz
INFO    | added library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/rf/Library/Caches/TemporaryItems/avd/running/pid_9540.ini

PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR: stdout: INFO    | boot completed

PIXELS_CATCHER::UTIL_EMULATOR: stdout: INFO    | boot time 18726 ms
INFO    | Increasing screen off timeout, logcat buffer size to 2M.

PIXELS_CATCHER::UTIL_EMULATOR: stdout: INFO    | Revoking microphone permissions for Google App.

PIXELS_CATCHER: Emulator started
PIXELS_CATCHER: Installing APK
PIXELS_CATCHER::UTIL_EMULATOR: Installing apk [/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/android/app/build/outputs/apk/release/app-release.apk]
PIXELS_CATCHER::UTIL_EMULATOR: Uninstalling com.issuespixelscatcher
PIXELS_CATCHER::UTIL_EMULATOR: Checking if [com.issuespixelscatcher] is installed
PIXELS_CATCHER::UTIL_EMULATOR: Package [com.issuespixelscatcher] is Installed
PIXELS_CATCHER::UTIL_EMULATOR: Uninstalling completed
PIXELS_CATCHER::UTIL_EMULATOR: Installed Performing Streamed Install
Success

PIXELS_CATCHER: APK installed
PIXELS_CATCHER: Starting application
PIXELS_CATCHER::UTIL_EMULATOR: Starting application [com.issuespixelscatcher]
PIXELS_CATCHER::UTIL_EMULATOR: Application started
PIXELS_CATCHER: Application started
PIXELS_CATCHER ERROR: Stop tests by timeout

==> All tests completed: <==
┌─────────┐
│ (index) │
├─────────┤
└─────────┘

==> Summary: <==
┌─────────┬───────────────────┬─────────────────────────────────┐
│ (index) │         0         │                1                │
├─────────┼───────────────────┼─────────────────────────────────┤
│    0    │   'Total tests'   │                0                │
│    1    │  'Passed tests'   │                0                │
│    2    │  'Skipped tests'  │                0                │
│    3    │  'Failed tests'   │                0                │
│    4    │ 'Min render time' │ '1.7976931348623157e+308ms (-)' │
│    5    │ 'Max render time' │         '5e-324ms (-)'          │
└─────────┴───────────────────┴─────────────────────────────────┘
PIXELS_CATCHER: Stopping the server and emulator
PIXELS_CATCHER::UTIL_EMULATOR: Stopping active device
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::SERVER: Server closed!
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator, stderr: WARNING | Not saving state: RAM not mapped as shared
```

_Pixel_4_API_24 (API 24, ABI x86, Android 7.0 (Google APIs))_
Emulator starts but app is not being started. Stuck in "awaiting when device is booted", times out after some time.
Console output:
```
PIXELS_CATCHER: Starting with [release] configuration for [android]
PIXELS_CATCHER: Config
{
  "activityName": ".MainActivity",
  "deviceName": "Pixel_4_XL_API_24",
  "packageName": "com.issuespixelscatcher",
  "snapshotsPath": "./snapshotsImages",
  "release": {
    "deviceParams": [
      "-no-audio",
      "-no-snapshot"
    ],
    "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
  }
}
PIXELS_CATCHER: Starting with:
  - activityName: [.MainActivity]
  - appFile: [./android/app/build/outputs/apk/release/app-release.apk]
  - deviceName: [Pixel_4_XL_API_24]
  - deviceParams: [-no-audio,-no-snapshot]
  - packageName: [com.issuespixelscatcher]
  - snapshotsPath: [./snapshotsImages]
  - canStopDevice: [undefined]
  - port: [undefined]
  - locale: [undefined]
PIXELS_CATCHER: Starting in ci mode
PIXELS_CATCHER: Starting server
PIXELS_CATCHER: Start emulator [Pixel_4_XL_API_24]
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: No active devices
PIXELS_CATCHER::UTIL_EMULATOR: Starting emulator [Pixel_4_XL_API_24]
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
- waiting for device -
PIXELS_CATCHER::SERVER: server is listening on port [3000]
PIXELS_CATCHER::UTIL_EMULATOR: stdout: INFO    | configAndStartRenderer: setting vsync to 60 hz
INFO    | added library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/rf/Library/Caches/TemporaryItems/avd/running/pid_9786.ini

PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
...
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator in 30 seconds. Check your emulator. Or try to run it with "-no-snapshot"
```

**Additional context**
I set up a standard react-native project using npx init to reproduce the bug and made the following changes:
**./pixels-catcher.json**
```
{
  "android": {
    "activityName": ".MainActivity",
    "deviceName": "Pixel_4_XL_API_30",
    "packageName": "com.issuespixelscatcher",
    "snapshotsPath": "./snapshotsImages",
    "release": {
      "deviceParams": ["-no-audio", "-no-snapshot"],
      "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
    }
  },
  "canStopDevice": true,
  "logLevel": "v"
}
```

**./indexSnapshot.js**
```
import {
  registerSnapshot,
  runSnapshots,
  Snapshot,
} from 'pixels-catcher';
import { Text } from 'react-native';
import React from 'react';
import { name as appName } from './app.json';

class AppSnapshot extends Snapshot {
  static snapshotName = 'SnapshotTest';

  renderContent() {
    return <Text>Test</Text>;
  }
}

registerSnapshot(AppSnapshot);

runSnapshots(appName);
```

**./android/app/build.gradle**
```
...
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
    entryFile: System.getProperty("entryFile") ?: "index.js",
    bundleInDebug: System.getProperty("bundleInDebug") ? System.getProperty("bundleInDebug").toBoolean() : false
]
...
```

I cannot tell if its a pixels-catcher bug or something else (with the emulators) is wrong. I've tried a lot of things like defining a port, different build.gradles, debug build etc without success. Would appreciate any help

**Comment by rumax** [comment]
Hi @renefitzke , thanks for reporting the issue. 

Can you, please, try to check if you can start/stop emulator from command line? 

Also as an alternative you can also define `"canStopDevice": false,` in config to disable start/restart of the emulator and run emulator manually. In case of CI  you can use the following script https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test-on-the-android-emulator.

**Comment by renefitzke** [comment]
Hey @rumax, thank you for your response.

Ive set `canStopDevice` to `false`, started the emulators manually in advance and tried again. Unfortunately without any luck.

The following are the logs:
**Pixel_4_XL_API_30**, pixels-catcher just terminates the running emulator
Emulator:
```
emulator -avd Pixel_4_XL_API_30
INFO    | Android emulator version 31.2.10.0 (build_id 8420304) (CL:N/A)
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/rf/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/rf/Library/Caches/TemporaryItems/avd/running/pid_5174.ini
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Shutting down gRPC endpoint
INFO    | Shutting down gRPC endpoint
```

pixels-catcher:
```
./node_modules/.bin/pixels-catcher android release
PIXELS_CATCHER: Starting with [release] configuration for [android]
PIXELS_CATCHER: Config
{
  "activityName": ".MainActivity",
  "deviceName": "Pixel_4_XL_API_30",
  "packageName": "com.issuespixelscatcher",
  "snapshotsPath": "./snapshotsImages",
  "release": {
    "deviceParams": [
      "-no-audio",
      "-no-snapshot"
    ],
    "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
  }
}
PIXELS_CATCHER: Starting with:
  - activityName: [.MainActivity]
  - appFile: [./android/app/build/outputs/apk/release/app-release.apk]
  - deviceName: [Pixel_4_XL_API_30]
  - deviceParams: [-no-audio,-no-snapshot]
  - packageName: [com.issuespixelscatcher]
  - snapshotsPath: [./snapshotsImages]
  - canStopDevice: [undefined]
  - port: [undefined]
  - locale: [undefined]
PIXELS_CATCHER: Starting in ci mode
PIXELS_CATCHER: Starting server
PIXELS_CATCHER: Start emulator [Pixel_4_XL_API_30]
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Other emulator already started
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Stopping emulator
PIXELS_CATCHER::UTIL_EMULATOR: Stopping active device
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
- waiting for device -
error: more than one device/emulator
PIXELS_CATCHER::UTIL_EXEC ERROR: Failed to execute [adb logcat -c], error: [Command failed: adb logcat -c
- waiting for device -
error: more than one device/emulator
] Error: Command failed: adb logcat -c
- waiting for device -
error: more than one device/emulator

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at exec (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/utils/exec.js:15:31)
    at TestReporter.collectDeviceLogs (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/utils/Reporter.js:140:32)
    at TestsRunner.<anonymous> (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:220:32)
    at step (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:33:23)
    at Object.next (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:14:53)
    at /Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:4:12) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2d 20 77 61 69 74 69 6e 67 20 66 6f 72 20 64 65 76 69 63 65 20 2d 0a 65 72 72 6f 72 3a 20 6d 6f 72 65 20 74 68 61 6e 20 6f 6e 65 20 64 65 76 69 63 65 ... 10 more bytes>
  ],
  pid: 5210,
  stdout: <Buffer >,
  stderr: <Buffer 2d 20 77 61 69 74 69 6e 67 20 66 6f 72 20 64 65 76 69 63 65 20 2d 0a 65 72 72 6f 72 3a 20 6d 6f 72 65 20 74 68 61 6e 20 6f 6e 65 20 64 65 76 69 63 65 ... 10 more bytes>
}
PIXELS_CATCHER::SERVER: server is listening on port [3000]
PIXELS_CATCHER::UTIL_EMULATOR: Active device stopped
PIXELS_CATCHER::UTIL_EMULATOR: Starting emulator [Pixel_4_XL_API_30]
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator, stderr: WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
```
---

**Pixel_4_XL_API_28**, pixels-catcher terminates and restarts the emulator
Emulator:
```
emulator -avd Pixel_4_XL_API_28
INFO    | Android emulator version 31.2.10.0 (build_id 8420304) (CL:N/A)
INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/rf/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/rf/Library/Caches/TemporaryItems/avd/running/pid_5524.ini
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Shutting down gRPC endpoint
INFO    | Shutting down gRPC endpoint
```

pixels-catcher:
```
./node_modules/.bin/pixels-catcher android release                    
PIXELS_CATCHER: Starting with [release] configuration for [android]
PIXELS_CATCHER: Config
{
  "activityName": ".MainActivity",
  "deviceName": "Pixel_4_XL_API_28",
  "packageName": "com.issuespixelscatcher",
  "snapshotsPath": "./snapshotsImages",
  "release": {
    "deviceParams": [
      "-no-audio",
      "-no-snapshot"
    ],
    "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
  }
}
PIXELS_CATCHER: Starting with:
  - activityName: [.MainActivity]
  - appFile: [./android/app/build/outputs/apk/release/app-release.apk]
  - deviceName: [Pixel_4_XL_API_28]
  - deviceParams: [-no-audio,-no-snapshot]
  - packageName: [com.issuespixelscatcher]
  - snapshotsPath: [./snapshotsImages]
  - canStopDevice: [undefined]
  - port: [undefined]
  - locale: [undefined]
PIXELS_CATCHER: Starting in ci mode
PIXELS_CATCHER: Starting server
PIXELS_CATCHER: Start emulator [Pixel_4_XL_API_28]
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Other emulator already started
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Stopping emulator
PIXELS_CATCHER::UTIL_EMULATOR: Stopping active device
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
- waiting for device -
error: more than one device/emulator
PIXELS_CATCHER::UTIL_EXEC ERROR: Failed to execute [adb logcat -c], error: [Command failed: adb logcat -c
- waiting for device -
error: more than one device/emulator
] Error: Command failed: adb logcat -c
- waiting for device -
error: more than one device/emulator

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at exec (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/utils/exec.js:15:31)
    at TestReporter.collectDeviceLogs (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/utils/Reporter.js:140:32)
    at TestsRunner.<anonymous> (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:220:32)
    at step (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:33:23)
    at Object.next (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:14:53)
    at /Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rf/Workspace/RNTestProject/IssuesPixelsCatcher/node_modules/pixels-catcher/lib/runner/TestsRunner.js:4:12) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2d 20 77 61 69 74 69 6e 67 20 66 6f 72 20 64 65 76 69 63 65 20 2d 0a 65 72 72 6f 72 3a 20 6d 6f 72 65 20 74 68 61 6e 20 6f 6e 65 20 64 65 76 69 63 65 ... 10 more bytes>
  ],
  pid: 5609,
  stdout: <Buffer >,
  stderr: <Buffer 2d 20 77 61 69 74 69 6e 67 20 66 6f 72 20 64 65 76 69 63 65 20 2d 0a 65 72 72 6f 72 3a 20 6d 6f 72 65 20 74 68 61 6e 20 6f 6e 65 20 64 65 76 69 63 65 ... 10 more bytes>
}
PIXELS_CATCHER::SERVER: server is listening on port [3000]
PIXELS_CATCHER::UTIL_EMULATOR: Active device stopped
PIXELS_CATCHER::UTIL_EMULATOR: Starting emulator [Pixel_4_XL_API_28]
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator, stderr: WARNING | cannot add library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
```
---

**Pixel_4_XL_API_24**, pixels-catcher terminates and restarts the emulator
Emulator:
```
emulator -avd Pixel_4_XL_API_24
INFO    | Android emulator version 31.2.10.0 (build_id 8420304) (CL:N/A)
INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/rf/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/rf/Library/Caches/TemporaryItems/avd/running/pid_4159.ini
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Shutting down gRPC endpoint
INFO    | Shutting down gRPC endpoint
```

pixels-catcher:
```
./node_modules/.bin/pixels-catcher android release
PIXELS_CATCHER: Starting with [release] configuration for [android]
PIXELS_CATCHER: Config
{
  "activityName": ".MainActivity",
  "deviceName": "Pixel_4_XL_API_24",
  "packageName": "com.issuespixelscatcher",
  "snapshotsPath": "./snapshotsImages",
  "release": {
    "deviceParams": [
      "-no-audio",
      "-no-snapshot"
    ],
    "appFile": "./android/app/build/outputs/apk/release/app-release.apk"
  }
}
PIXELS_CATCHER: Starting with:
  - activityName: [.MainActivity]
  - appFile: [./android/app/build/outputs/apk/release/app-release.apk]
  - deviceName: [Pixel_4_XL_API_24]
  - deviceParams: [-no-audio,-no-snapshot]
  - packageName: [com.issuespixelscatcher]
  - snapshotsPath: [./snapshotsImages]
  - canStopDevice: [undefined]
  - port: [undefined]
  - locale: [undefined]
PIXELS_CATCHER: Starting in ci mode
PIXELS_CATCHER: Starting server
PIXELS_CATCHER: Start emulator [Pixel_4_XL_API_24]
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Other emulator already started
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Stopping emulator
PIXELS_CATCHER::UTIL_EMULATOR: Stopping active device
PIXELS_CATCHER::UTIL_EMULATOR: Get active device
PIXELS_CATCHER::UTIL_EMULATOR: Active device emulator-5554
PIXELS_CATCHER::SERVER: server is listening on port [3000]
PIXELS_CATCHER::UTIL_EMULATOR: Active device stopped
PIXELS_CATCHER::UTIL_EMULATOR: Starting emulator [Pixel_4_XL_API_24]
PIXELS_CATCHER::UTIL_EMULATOR: awaiting when device is booted
PIXELS_CATCHER::UTIL_EMULATOR ERROR: Failed to load emulator, stderr: WARNING | cannot add library /Users/rf/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
```
